Repository bedita/bedita, pull requests merged in 2018-11, with the labels that each got.

#1559 VTT Captions
  bedita-app/config/sql/upgrade/1-3.8-to-3.9-schema.sql
  bedita-app/models/objects/caption.php
  bedita-app/models/objects/content/video.php
  bedita-app/views/helpers/be_embed_html5.php
  bedita-app/views/multimedia/inc/form.tpl
  bedita-app/views/multimedia/inc/form_captions.tpl
  bedita-app/webroot/css/module.multimedia.css
  bedita-app/webroot/js/libs/webvtt/parser.js
Labels: Topic - Core, Type - New Feature

#1554 #1552 feat: default fields from config per object type
  config/app.default.php
  plugins/BEdita/Core/src/Model/Behavior/DataCleanupBehavior.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/DataCleanupBehaviorTest.php
Labels: Priority - Normal

#1567 custom types from config for multimedia module
  bedita-app/config/bedita.cfg.php.sample
  bedita-app/controllers/components/be_file_handler.php
  bedita-app/controllers/modules/multimedia_controller.php
  bedita-app/locale/deu/LC_MESSAGES/default.po
  bedita-app/locale/eng/LC_MESSAGES/default.po
  bedita-app/locale/fra/LC_MESSAGES/default.po
  bedita-app/locale/ita/LC_MESSAGES/default.po
  bedita-app/locale/master.pot
  bedita-app/locale/por/LC_MESSAGES/default.po
  bedita-app/locale/spa/LC_MESSAGES/default.po
Labels: Priority - High, Type - New Feature
