Repository bedita/bedita, pull requests merged in 2018-05, with the labels that each got.

#1468 Included deleted objects #1466
  plugins/BEdita/API/src/TestSuite/IntegrationTestCase.php
  plugins/BEdita/API/tests/IntegrationTest/AssociatedEntitiesTest.php
  plugins/BEdita/API/tests/TestCase/TestSuite/IntegrationTestCaseTest.php
  plugins/BEdita/Core/src/Model/Action/UpdateAssociatedAction.php
  plugins/BEdita/Core/src/Model/Action/UpdateRelatedObjectsAction.php
  plugins/BEdita/Core/src/Model/Behavior/RelationsBehavior.php
  plugins/BEdita/Core/src/Model/Table/ObjectsTable.php
Labels: Priority - High, Topic - ORM, Type - Bug

#1469 Relations inheritance #1349
  plugins/BEdita/API/src/Controller/ObjectsController.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/RelationsControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/ObjectsControllerTest.php
  plugins/BEdita/Core/src/Model/Behavior/RelationsBehavior.php
  plugins/BEdita/Core/src/Model/Entity/ObjectType.php
  plugins/BEdita/Core/src/Model/Table/ObjectTypesTable.php
  plugins/BEdita/Core/src/Model/Table/RelationsTable.php
  plugins/BEdita/Core/tests/Fixture/RelationTypesFixture.php
  plugins/BEdita/Core/tests/Fixture/RelationsFixture.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/ObjectTypeTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectTypesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/RelationsTableTest.php
Labels: Priority - High, Topic - ORM, Type - Enhancement

#1472 Fix foreign key `cascade` on delete for `objects`
  plugins/BEdita/API/tests/TestCase/Controller/ObjectsControllerTest.php
  plugins/BEdita/Core/config/Migrations/20180507095822_DeleteRestrict.php
  plugins/BEdita/Core/config/Migrations/schema-dump-default.lock
  plugins/BEdita/Core/tests/Fixture/ObjectsFixture.php
Labels: Priority - High, Topic - Database, Type - Bug

#1473 Prevent login from blocked, deleted and off users
  plugins/BEdita/API/src/Controller/LoginController.php
  plugins/BEdita/API/tests/TestCase/Controller/LoginControllerTest.php
  plugins/BEdita/Core/src/Model/Table/UsersTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php
Labels: Priority - High, Topic - Security, Type - Bug

#1477 Fix multiple issues with Folders' relationships #1471
  plugins/BEdita/API/src/Controller/FoldersController.php
  plugins/BEdita/API/src/Controller/ResourcesController.php
  plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php
Labels: Priority - High, Topic - API, Type - Bug

#1481 Prevent ghost folders #1479
  plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php
  plugins/BEdita/Core/src/Model/Action/AddAssociatedAction.php
  plugins/BEdita/Core/src/Model/Action/SetAssociatedAction.php
  plugins/BEdita/Core/src/Model/Table/FoldersTable.php
  plugins/BEdita/Core/src/Model/Table/ObjectsTable.php
  plugins/BEdita/Core/src/Model/Table/TreesTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddAssociatedActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SetAssociatedActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/FolderTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/TreesTableTest.php
Labels: Priority - High, Topic - API, Topic - Core, Type - Bug

#1483 Tree maintenance shell #1476
  plugins/BEdita/Core/src/Model/Table/ObjectsTable.php
  plugins/BEdita/Core/src/Model/Table/TreesTable.php
  plugins/BEdita/Core/src/Shell/Task/CheckTreeTask.php
  plugins/BEdita/Core/src/Shell/Task/RecoverTreeTask.php
  plugins/BEdita/Core/src/Shell/TreeShell.php
  plugins/BEdita/Core/tests/TestCase/Shell/Task/CheckTreeTaskTest.php
  plugins/BEdita/Core/tests/TestCase/Shell/Task/RecoverTreeTaskTest.php
Labels: Priority - Normal, Topic - Shell, Type - New Feature
