Repository bedita/bedita, pull requests merged in 2018-10, with the labels that each got.

#1541 `parent` filter using name
  plugins/BEdita/API/tests/IntegrationTest/FilterQueryStringTest.php
  plugins/BEdita/Core/src/Model/Table/ObjectTypesTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectTypesTableTest.php
Labels: Priority - Normal, Topic - API

#1543 feat: php 7.1 as minimum version
  .travis.yml
  README.md
  composer.json
  config/requirements.php
  plugins/BEdita/API/.travis.yml
  plugins/BEdita/API/composer.json
  plugins/BEdita/Core/.travis.yml
  plugins/BEdita/Core/composer.json
Labels: Priority - High

#1544 Read application first
  plugins/BEdita/API/src/Auth/EndpointAuthorize.php
  plugins/BEdita/API/src/Controller/AppController.php
  plugins/BEdita/API/tests/TestCase/Auth/EndpointAuthorizeTest.php
  plugins/BEdita/API/tests/TestCase/Controller/AppControllerTest.php
Labels: Priority - Critical, Topic - Authentication

#1546 fix: after save section clear only cache of parent
  bedita-app/models/behaviors/cacheable.php
  bedita-app/models/objects/collection/section.php
Labels: Priority - High, Topic - Core, Type - Bug

#1549 Make user tokens types configurable
  plugins/BEdita/Core/src/Model/Table/UserTokensTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/UserTokensTableTest.php
Labels: Priority - High, Topic - Core, Type - Enhancement

#1548 Avoid `status` filter on resources
  plugins/BEdita/Core/src/Model/Action/ListRelatedObjectsAction.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/ListRelatedObjectsActionTest.php
Labels: Priority - High, Topic - Core, Type - Bug

#1553 Add field `note` for Documents
  bedita-app/config/bedita.ini.php
  bedita-app/views/documents/inc/form.tpl
Labels: Priority - Normal, Topic - UI, Type - Enhancement

#1557 Fix fatal error on model save if object cache is disabled
  bedita-app/models/behaviors/cacheable.php
Labels: Priority - High, Topic - ORM, Type - Bug
