Repository bedita/bedita, pull requests merged in 2018-09, with the labels that each got.

#1536 feat: included in related (query string lang)
  plugins/BEdita/API/src/Controller/ObjectsController.php
  plugins/BEdita/API/tests/IntegrationTest/I18nTest.php
Labels: Priority - High, Topic - API

#1538 Refactor cache using Redis hashes
  bedita-app/controllers/modules/translations_controller.php
  bedita-app/libs/be_object_cache.php
  bedita-app/models/behaviors/cacheable.php
  bedita-app/models/behaviors/delete_object.php
  bedita-app/vendors/shells/cache.php
  cake/libs/cache/file.php
  cake/libs/cache/redis.php
Labels: Priority - High, Topic - Core, Topic - Performance, Type - Enhancement

#1539 `profiles.email` non unique index
  plugins/BEdita/Core/config/Migrations/20180918153133_RemoveUniqueEmail.php
  plugins/BEdita/Core/config/Migrations/schema-dump-default.lock
  plugins/BEdita/Core/src/Model/Table/ProfilesTable.php
  plugins/BEdita/Core/src/Model/Table/UsersTable.php
  plugins/BEdita/Core/src/Model/Validation/ProfilesValidator.php
  plugins/BEdita/Core/src/Model/Validation/UsersValidator.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ProfilesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Validation/ProfilesValidatorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Validation/UsersValidatorTest.php
Labels: Priority - High, Topic - Database

#1533 Existing user signup
  plugins/BEdita/Core/src/Model/Action/SignupUserAction.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SignupUserActionTest.php
Labels: Priority - High, Topic - Authentication
