Repository bedita/bedita, pull requests merged in 2018-08, with the labels that each got.

#1525 Update child position with `POST` action as well
  plugins/BEdita/API/src/Controller/ObjectsController.php
  plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php
  plugins/BEdita/Core/src/Model/Action/AddAssociatedAction.php
  plugins/BEdita/Core/src/Model/Table/FoldersTable.php
  plugins/BEdita/Core/src/Model/Table/ObjectsTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddAssociatedActionTest.php
Labels: Priority - High, Topic - ORM, Type - Bug

#1465 fix: users validation, empty password now allowed, if present
  plugins/BEdita/Core/src/Model/Validation/UsersValidator.php
Labels: Priority - High, Topic - Security

#1522 Fix date & datetime input
  plugins/BEdita/API/tests/IntegrationTest/DateTimeTest.php
  plugins/BEdita/Core/config/bootstrap.php
  plugins/BEdita/Core/src/Database/Type/DateTimeType.php
  plugins/BEdita/Core/src/Database/Type/DateType.php
  plugins/BEdita/Core/src/Model/Table/AsyncJobsTable.php
  plugins/BEdita/Core/src/Model/Table/DateRangesTable.php
  plugins/BEdita/Core/src/Model/Validation/ObjectsValidator.php
  plugins/BEdita/Core/src/Model/Validation/ProfilesValidator.php
  plugins/BEdita/Core/src/Model/Validation/Validation.php
  plugins/BEdita/Core/tests/TestCase/Database/Type/DateTimeTypeTest.php
  plugins/BEdita/Core/tests/TestCase/Database/Type/DateTypeTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Validation/ValidationTest.php
Labels: Priority - High, Topic - API, Topic - ORM, Type - Bug

#1526 Replace JSON Schema validation libraries
  plugins/BEdita/API/tests/IntegrationTest/RelationshipsParamsTest.php
  plugins/BEdita/API/tests/IntegrationTest/StatusLevelTest.php
  plugins/BEdita/Core/composer.json
  plugins/BEdita/Core/src/Model/Behavior/RelationsBehavior.php
  plugins/BEdita/Core/src/Model/Entity/Property.php
  plugins/BEdita/Core/src/Model/Validation/Validation.php
  plugins/BEdita/Core/src/Model/Validation/schemas/draft-06.json
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectRelationsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Validation/ValidationTest.php
Labels: Priority - Normal, Topic - Vendors, Type - Task
