Repository bedita/bedita, pull requests merged in 2018-04, with the labels that each got.

#1443 feat: use personal access token for API authorization
  bedita-app/vendors/shells/deploy.php
Labels: Priority - High, Topic - Security

#1448 Add default `title` for profiles and users
  plugins/BEdita/Core/src/Model/Table/ProfilesTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ProfilesTableTest.php
Labels: Priority - Normal, Type - Enhancement

#1452 fix: card always reachable
  bedita-app/controllers/components/api_validator.php
  bedita-app/models/account/user.php
Labels: Priority - High, Topic - API, Type - Bug

#1456 Routing rules change
  config/routes.php
  plugins/BEdita/API/src/Controller/ObjectsController.php
  plugins/BEdita/API/src/Controller/ResourcesController.php
  plugins/BEdita/Core/src/Model/Entity/JsonApiAdminTrait.php
  plugins/BEdita/Core/src/Model/Entity/JsonApiModelTrait.php
  plugins/BEdita/Core/src/Model/Entity/JsonApiTrait.php
  plugins/BEdita/Core/src/Plugin.php
  plugins/BEdita/Core/src/Utility/JsonApiSerializable.php
Labels: Priority - High, Topic - API, Type - Bug

#1457 Dispatch event on tree changes
  bedita-app/models/tree.php
Labels: Priority - High, Topic - Core, Type - Enhancement

#1458 Don't list deleted objects in `children` and `parents
  plugins/BEdita/API/tests/IntegrationTest/ParentsRelationshipTest.php
  plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php
  plugins/BEdita/Core/src/Model/Action/ListRelatedFoldersAction.php
  plugins/BEdita/Core/src/Model/Action/ListRelatedObjectsAction.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/ListRelatedFoldersActionTest.php
Labels: Priority - High, Type - Bug
