Repository bedita/bedita, pull requests merged in 2019-01, with the labels that each got.

#1574 Fix usage of return value from Video provider helper
  bedita-app/views/helpers/be_embed_media.php
Labels: Priority - High, Type - Bug

#1572 Make `params` optional when updating relations
  plugins/BEdita/API/src/Model/Action/UpdateAssociatedAction.php
  plugins/BEdita/API/tests/IntegrationTest/RelationshipsParamsTest.php
  plugins/BEdita/API/tests/TestCase/Controller/ResourcesControllerTest.php
  plugins/BEdita/API/tests/TestCase/Model/Action/UpdateAssociatedActionTest.php
  plugins/BEdita/Core/src/Model/Action/AddAssociatedAction.php
  plugins/BEdita/Core/src/Model/Action/AddRelatedObjectsAction.php
  plugins/BEdita/Core/src/Model/Action/AssociatedTrait.php
  plugins/BEdita/Core/src/Model/Action/RemoveAssociatedAction.php
  plugins/BEdita/Core/src/Model/Action/SetAssociatedAction.php
  plugins/BEdita/Core/src/Model/Action/SetRelatedObjectsAction.php
  plugins/BEdita/Core/src/Model/Action/UpdateAssociatedAction.php
  plugins/BEdita/Core/src/Model/Action/UpdateRelatedObjectsAction.php
  plugins/BEdita/Core/src/Model/Table/ObjectRelationsTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddAssociatedActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/RemoveAssociatedActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/RemoveRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SetAssociatedActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SetRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectRelationsTableTest.php
  tests/bootstrap.php
Labels: Priority - High, Topic - ORM, Type - Bug

#1576 #1575 update tree paths of section's children
  bedita-app/controllers/api_base_controller.php
  bedita-app/models/tree.php
Labels: Priority - High, Topic - ORM, Type - Bug

#1577 [minor] fix: get all children when checks on permissions are disabled
  bedita-app/controllers/api_base_controller.php
  bedita-app/controllers/components/api_validator.php
Labels: Priority - High, Topic - API, Type - Bug

#1583 Restore optional parameters for new relations that allow empty objects #1582
  plugins/BEdita/API/tests/IntegrationTest/RelationshipsParamsTest.php
  plugins/BEdita/Core/src/Model/Table/LocationsTable.php
  plugins/BEdita/Core/src/Model/Table/ObjectRelationsTable.php
Labels: Priority - High, Topic - ORM, Type - Bug

#1585 #1584 feat: refactored method updateSiblingsPriority
  bedita-app/controllers/api_base_controller.php
Labels: Priority - High, Type - Enhancement
