Repository bedita/bedita, pull requests merged in 2019-06, with the labels that each got.

#1608 Avoid potential SQL injection when updating relations with params
  bedita-app/models/object_relation.php
  bedita-app/models/objects/b_e_object.php
  bedita-app/tests/cases/models/object_relation.test.php
Labels: Priority - Critical, Topic - ORM, Topic - Security, Type - Bug

#1610 Add and use mask utility
  bedita-app/app_controller.php
  bedita-app/config/bootstrap.php
  bedita-app/controllers/components/api_auth.php
  bedita-app/controllers/components/be_auth.php
  bedita-app/libs/mask.php
Labels: Topic - Core, Type - Task

#1611 #1045 fix: allow user auth if APIs are protected
  bedita-app/controllers/api_base_controller.php
Labels: Priority - High, Topic - API, Type - Bug

#1612 Fix `DefaultValues` config on core types
  plugins/BEdita/API/tests/IntegrationTest/DefaultValuesTest.php
  plugins/BEdita/Core/src/Model/Table/LocationsTable.php
  plugins/BEdita/Core/src/Model/Table/MediaTable.php
Labels: Priority - High, Topic - ORM, Type - Bug
