Repository bedita/bedita, pull requests merged in 2020-04, with the labels that each got.

#1672 Fix entity virtual props recursion
  plugins/BEdita/Core/src/Model/Behavior/CustomPropertiesBehavior.php
  plugins/BEdita/Core/src/Model/Entity/ObjectEntity.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/FolderTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/ObjectEntityTest.php
Labels: Priority - High, Type - Bug

#1650 Fix wrong count using elasticsearch and SQL conditions
  bedita-app/app_model.php
Labels: Priority - High, Topic - Core, Type - Bug

#1678 Fix some issue with BeToolbar
  bedita-app/views/elements/toolbar.tpl
  bedita-app/views/helpers/be_toolbar.php
Labels: Priority - Normal, Topic - Core, Type - Bug

#1681 Limit uname max length
  plugins/BEdita/Core/src/Model/Behavior/UniqueNameBehavior.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/UniqueNameBehaviorTest.php
Labels: Topic - Core, Type - Bug

#1679 Avoid `included` repetitions
  plugins/BEdita/API/src/View/JsonApiView.php
  plugins/BEdita/API/tests/TestCase/View/JsonApiViewTest.php
Labels: Priority - Normal, Topic - API, Type - Bug
