Repository bedita/bedita, pull requests merged in 2020-10, with the labels that each got.

#1731 feat: relation params setter
  plugins/BEdita/API/tests/TestCase/Controller/Model/RelationsControllerTest.php
  plugins/BEdita/Core/src/Model/Entity/Relation.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/RelationTest.php
Labels: Priority - High

#1734 Allow to use specific composer version
  .travis.yml
Labels: Priority - High, Type - Task

#1735 Add external_auth info in users meta
  plugins/BEdita/API/tests/IntegrationTest/FieldsQueryStringTest.php
  plugins/BEdita/API/tests/TestCase/Controller/AppControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/RolesControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/UsersControllerTest.php
  plugins/BEdita/API/tests/TestCase/View/JsonApiViewTest.php
  plugins/BEdita/Core/src/Model/Entity/User.php
  plugins/BEdita/Core/src/Model/Table/ExternalAuthTable.php
  plugins/BEdita/Core/tests/Fixture/AuthProvidersFixture.php
  plugins/BEdita/Core/tests/Fixture/ExternalAuthFixture.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiTraitTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/UserTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ExternalAuthTableTest.php
Labels: Priority - High, Topic - API, Type - Enhancement
