Repository bedita/bedita, pull requests merged in 2022-09, with the labels that each got.

#1931 Don't show all objects when searching without query
  bedita-app/controllers/frontend_controller.php
Labels: Type - Bug, Topic - Frontend, Priority - High

#1930 Do not fail saving objects with relation priority as empty string
  bedita-app/models/objects/b_e_object.php
Labels: Type - Bug, Topic - Core, Priority - High

#1932 Fix docker stuff for 5-salix
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: Type - Bug, Priority - Normal, Topic - Integration

#1933 Use PHP 8.1 in docker image
  Dockerfile
  docker-entrypoint.sh
Labels: Topic - Integration

#1934 Fix ObjectHanlders save with custom properties
  plugins/BEdita/Core/src/Utility/ObjectsHandler.php
  plugins/BEdita/Core/tests/TestCase/Utility/ObjectsHandlerTest.php
Labels: Type - Bug

#1935 Add release workflow
  .github/workflows/components.yml
  .github/workflows/filter-components.yml
  .github/workflows/release.yml
  CHANGES.md
Labels: Topic - Integration

#1936 Fix error on multiple anonymizations
  plugins/BEdita/Core/src/Model/Table/UsersTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php
Labels: Type - Bug, Topic - Core, release:patch

#1937 Skip docker image creation on missing release
  .github/workflows/release.yml
Labels: Topic - Integration, release:patch

#1939 Fix project model diff on properties with same name
  plugins/BEdita/Core/src/Utility/ProjectModel.php
  plugins/BEdita/Core/tests/TestCase/Utility/ProjectModelTest.php
Labels: Type - Bug, release:patch
