Repository bedita/bedita, pull requests merged in 2022-01, with the labels that each got.

#1850 Create writable bedita_core folder for cache
  src/Console/Installer.php
Labels: Type - Task, Priority - Normal

#1852 Roles as stdClass
  plugins/BEdita/API/src/Controller/LoginController.php
Labels: Type - Bug, Priority - High

#1851 Comments controller index comment type only
  bedita-app/controllers/modules/comments_controller.php
Labels: Topic - Modules, Priority - Normal

#1853 update composer dependency bedita/dev-tools to 1.5.*
  composer.json
Labels: Type - Enhancement, Priority - Normal, Topic - Integration

#1857 Disable staging toolbar
  bedita-app/views/elements/messages.tpl
  bedita-app/views/helpers/be_front.php
Labels: Type - Enhancement, Topic - Core, Topic - Frontend, Priority - Normal

#1858 Introduce autocomplete for tags in object view
  bedita-app/controllers/modules/tags_controller.php
  bedita-app/views/elements/form_tags.tpl
  bedita-app/webroot/js/beditaUI.js
Labels: Type - Enhancement, Topic - Modules, Priority - Normal
