Repository bedita/bedita, pull requests merged in 2023-06, with the labels that each got.

#1907 Add methods to expand and compact priorities list
  plugins/BEdita/Core/src/Model/Behavior/PriorityBehavior.php
  plugins/BEdita/Core/tests/Fixture/ObjectRelationsFixture.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/CountRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/PriorityBehaviorTest.php
Labels: Topic - Core, Priority - Normal, release:minor

#2018 Add methods to expand and compact priorities list
  plugins/BEdita/Core/src/Model/Behavior/PriorityBehavior.php
  plugins/BEdita/Core/tests/Fixture/ObjectRelationsFixture.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/CountRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/PriorityBehaviorTest.php
Labels: Topic - Core, Priority - Normal, release:minor

#2020 New `additionalHeaders` configuration for OAuth2 API requests
  plugins/BEdita/Core/src/Utility/OAuth2.php
Labels: Topic - API, Topic - Integration, release:patch

#2021 BaseApplication middleware signature
  plugins/BEdita/API/src/App/BaseApplication.php
Labels: Priority - High, release:patch

#2024 Add `delay` option to `QueueManager` to avoid job lock issues
  config/app_local.example.php
  plugins/BEdita/Core/src/Model/Table/AsyncJobsTable.php
Labels: Priority - High, Topic - Performance, Topic - Integration, release:patch
