Repository bedita/bedita, pull requests merged in 2023-03, with the labels that each got.

#1985 Allow dot separated strings in username
  plugins/BEdita/Core/src/Model/Validation/UsersValidator.php
  plugins/BEdita/Core/tests/TestCase/Model/Validation/UsersValidatorTest.php
Labels: Type - Bug, Topic - Core, Priority - High, release:patch

#1986 Fixes public loc in sitemap generator
  bedita-app/controllers/frontend_controller.php
  bedita-app/views/pages/sitemap_xml.tpl
Labels: Type - Bug, Topic - Frontend

#1989 Use v3 of checkout and cache
  .github/workflows/filter-components.yml
  .github/workflows/tests.yml
Labels: Topic - Integration

#1990 Use v3 of checkout and cache
  .github/workflows/filter-components.yml
  .github/workflows/tests.yml
Labels: Topic - Integration

#1991 Use v3 codecov-action and upload-artifact, replace set-output with GITHUB_OUTPUT
  .github/workflows/tests.yml
Labels: Topic - Tests, Topic - Integration

#1992 Use v3 codecov-action and upload-artifact, replace set-output with GITHUB_OUTPUT
  .github/workflows/tests.yml
Labels: Topic - Tests, Topic - Integration

#1988 Add role priority
  plugins/BEdita/API/tests/TestCase/Controller/AppControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/RolesControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/UsersControllerTest.php
  plugins/BEdita/API/tests/TestCase/Model/Action/UpdateRelatedActionTest.php
  plugins/BEdita/API/tests/TestCase/Utility/JsonApiTest.php
  plugins/BEdita/API/tests/TestCase/View/JsonApiViewTest.php
  plugins/BEdita/API/tests/TestConstants.php
  plugins/BEdita/Core/config/Migrations/20230321112607_AddRolePriority.php
  plugins/BEdita/Core/config/Migrations/schema-dump-default.lock
  plugins/BEdita/Core/src/Model/Entity/Role.php
  plugins/BEdita/Core/src/Model/Table/RolesUsersTable.php
  plugins/BEdita/Core/tests/Fixture/RolesFixture.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SetRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SignupUserActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiTraitTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ExternalAuthTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/RolesUsersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/JsonSchemaTest.php
Labels: Priority - High, Topic - Security, release:minor

#1995 Fix signup: create user with role admin
  plugins/BEdita/Core/src/Model/Action/SignupUserAction.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SignupUserActionTest.php
Labels: Type - Bug, Priority - High, Topic - API, release:patch

#1996 Fix signup: create user with role admin
  plugins/BEdita/Core/src/Model/Action/SignupUserAction.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SignupUserActionTest.php
Labels: Type - Bug, Priority - High, Topic - API, release:patch

#1997 Refactor: `LoggedUser::setUserAdmin` and `LoggedUser::getUserAdmin`
  plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php
  plugins/BEdita/API/tests/TestCase/Model/Action/UpdateRelatedActionTest.php
  plugins/BEdita/API/tests/TestCase/TestSuite/IntegrationTestCaseTest.php
  plugins/BEdita/Core/src/Model/Action/SignupUserAction.php
  plugins/BEdita/Core/src/Utility/LoggedUser.php
  plugins/BEdita/Core/src/Utility/ObjectsHandler.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/DeleteObjectActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SetRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/HistoryBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/UniqueNameBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/UserModifiedBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/AnnotationsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ExternalAuthTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/FoldersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/LocationsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/MediaTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ProfilesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/RolesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/RolesUsersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/TreesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/LoggedUserTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/ObjectsHandlerTest.php
Labels: Type - Enhancement, Topic - Code Quality

#1998 Refactor: `LoggedUser::setUserAdmin` and `LoggedUser::getUserAdmin`
  plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php
  plugins/BEdita/API/tests/TestCase/Model/Action/UpdateRelatedActionTest.php
  plugins/BEdita/API/tests/TestCase/TestSuite/IntegrationTestCaseTest.php
  plugins/BEdita/Core/src/Model/Action/SignupUserAction.php
  plugins/BEdita/Core/src/Utility/LoggedUser.php
  plugins/BEdita/Core/src/Utility/ObjectsHandler.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/AddRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/DeleteObjectActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/SetRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/HistoryBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/UniqueNameBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/UserModifiedBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/AnnotationsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ExternalAuthTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/FoldersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/LocationsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/MediaTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectsTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ProfilesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/RolesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/RolesUsersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/TreesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/LoggedUserTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/ObjectsHandlerTest.php
Labels: Type - Enhancement, Topic - Code Quality

#1999 refactor: change objects description and body to be mediumtext
  plugins/BEdita/Core/config/Migrations/20230327104919_ChangeObjectsDescriptionBodySize.php
  plugins/BEdita/Core/config/Migrations/schema-dump-default.lock
  plugins/BEdita/Core/src/Model/Validation/ObjectsValidator.php
Labels: Type - Enhancement, release:patch
