Repository bedita/bedita, pull requests merged in 2024-09, with the labels that each got.

#2096 Feat: filter to re/index objects in a folder
  plugins/BEdita/Core/src/Command/BuildSearchIndexCommand.php
  plugins/BEdita/Core/tests/TestCase/Command/BuildSearchIndexCommandTest.php
Labels: Type - Enhancement, Topic - Shell, Priority - Normal, release:patch

#2095 Introduce custom `UserMailer`
  config/app_local.example.php
  plugins/BEdita/Core/src/Mailer/UserMailer.php
  plugins/BEdita/Core/src/Mailer/UserMailerInterface.php
  plugins/BEdita/Core/src/Mailer/UserMailerTrait.php
  plugins/BEdita/Core/src/Model/Action/ChangeCredentialsRequestAction.php
  plugins/BEdita/Core/src/Model/Action/SignupUserAction.php
  plugins/BEdita/Core/src/Model/Action/SignupUserActivationAction.php
  plugins/BEdita/Core/tests/TestCase/Mailer/UserMailerTraitTest.php
Labels: Topic - Integration

#2094 Delete multiple resources
  plugins/BEdita/API/config/routes.php
  plugins/BEdita/API/src/Controller/ObjectsController.php
  plugins/BEdita/API/src/Controller/ResourcesController.php
  plugins/BEdita/API/src/Controller/TrashController.php
  plugins/BEdita/API/tests/TestCase/Controller/ObjectsControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/ResourcesControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/TrashControllerTest.php
  plugins/BEdita/Core/src/Model/Action/DeleteEntitiesAction.php
  plugins/BEdita/Core/src/Model/Action/DeleteObjectsAction.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/DeleteEntitiesActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/DeleteObjectsActionTest.php
Labels: Topic - Core, Type - New Feature, Topic - API, release:minor

#2088 Feat: default relation params
  plugins/BEdita/API/src/Model/Action/UpdateAssociatedAction.php
  plugins/BEdita/API/tests/TestCase/Controller/AnnotationsControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/ProjectControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/RelationsControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/ObjectsControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/TranslationsControllerTest.php
  plugins/BEdita/API/tests/TestCase/Model/Action/UpdateAssociatedActionTest.php
  plugins/BEdita/API/tests/TestCase/Model/Action/UpdateRelatedActionTest.php
  plugins/BEdita/API/tests/TestCase/Utility/JsonApiTest.php
  plugins/BEdita/API/tests/TestConstants.php
  plugins/BEdita/Core/src/Model/Behavior/RelationsBehavior.php
  plugins/BEdita/Core/src/ORM/Association/RelatedTo.php
  plugins/BEdita/Core/tests/Fixture/ObjectRelationsFixture.php
  plugins/BEdita/Core/tests/Fixture/RelationTypesFixture.php
  plugins/BEdita/Core/tests/Fixture/RelationsFixture.php
  plugins/BEdita/Core/tests/TestCase/Command/ProjectModelCommandTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Action/CountRelatedObjectsActionTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/RelationsBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiTraitTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/ObjectEntityTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/ObjectTypeTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectTypesTableTest.php
  plugins/BEdita/Core/tests/TestCase/ORM/Association/RelatedToTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/ProjectModelTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/RelationsTest.php
Labels: Type - Enhancement, Priority - Normal, Topic - API, release:patch

#2097 Increase `config.content` column size to MEDIUMTEXT
  plugins/BEdita/Core/config/Migrations/20240919124057_ConfigContents.php
Labels: Topic - Database

#2082 Property default
  config/Migrations/schema-dump-default.lock
  plugins/BEdita/API/tests/TestCase/Controller/MediaControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/ProjectControllerTest.php
  plugins/BEdita/API/tests/TestCase/Controller/Model/PropertiesControllerTest.php
  plugins/BEdita/API/tests/TestConstants.php
  plugins/BEdita/Core/config/Migrations/20240626123658_UpdateProperties.php
  plugins/BEdita/Core/config/Migrations/schema-dump-default.lock
  plugins/BEdita/Core/src/Model/Entity/Property.php
  plugins/BEdita/Core/src/Utility/Properties.php
  plugins/BEdita/Core/tests/Fixture/PropertiesFixture.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/CustomPropertiesBehaviorTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Entity/ObjectTypeTest.php
  plugins/BEdita/Core/tests/TestCase/Model/Table/PropertiesTableTest.php
  plugins/BEdita/Core/tests/TestCase/Utility/ProjectModelTest.php
Labels: Type - Enhancement, Topic - Core

#2050 `objects_history` command
  plugins/BEdita/Core/src/Command/ObjectsHistoryCommand.php
  plugins/BEdita/Core/tests/TestCase/Command/ObjectsHistoryCommandTest.php
Labels: Topic - Core, Topic - Shell, Type - New Feature

#2084 Do not reindex entities that are not the primary saved entity
  plugins/BEdita/Core/src/Model/Behavior/SearchableBehavior.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/SearchableBehaviorTest.php
Labels: Type - Bug, Topic - ORM

#2098 CI codecov threshold 1%
  codecov.yml
Labels: Topic - Integration

#2052 JobsCommand (JobsShell deprecated)
  plugins/BEdita/Core/src/Command/JobsCommand.php
  plugins/BEdita/Core/src/Shell/JobsShell.php
  plugins/BEdita/Core/tests/TestCase/Command/JobsCommandTest.php
Labels: Type - Enhancement, Topic - Core, Topic - Shell

#2063 Add support for scopes in search adapters
  plugins/BEdita/Core/src/Model/Behavior/ObjectModelBehavior.php
  plugins/BEdita/Core/src/Model/Behavior/SearchableBehavior.php
  plugins/BEdita/Core/src/Model/Table/AnnotationsTable.php
  plugins/BEdita/Core/src/Model/Table/ApplicationsTable.php
  plugins/BEdita/Core/src/Model/Table/CategoriesTable.php
  plugins/BEdita/Core/src/Model/Table/ObjectTypesTable.php
  plugins/BEdita/Core/src/Model/Table/PropertiesTable.php
  plugins/BEdita/Core/src/Model/Table/PropertyTypesTable.php
  plugins/BEdita/Core/src/Model/Table/RelationsTable.php
  plugins/BEdita/Core/src/Model/Table/RolesTable.php
  plugins/BEdita/Core/src/Model/Table/TagsTable.php
  plugins/BEdita/Core/src/Model/Table/TranslationsTable.php
  plugins/BEdita/Core/tests/TestCase/Model/Behavior/SearchableBehaviorTest.php
Labels: Type - Enhancement, release:minor
