Repository bedita/bedita, pull requests merged in 2024-02, with the labels that each got.

#2046 `async_jobs_clean` command
  plugins/BEdita/Core/src/Command/AsyncJobsCleanCommand.php
  plugins/BEdita/Core/tests/TestCase/Command/AsyncJobsCleanCommandTest.php
Labels: Type - Enhancement, Topic - Core, Topic - Shell, release:minor

#2049 `objects_delete` command
  composer.json
  plugins/BEdita/Core/src/Command/ObjectsDeleteCommand.php
  plugins/BEdita/Core/tests/TestCase/Command/ObjectsDeleteCommandTest.php
Labels: Type - Enhancement, Topic - Core, Topic - Shell, release:minor

#2051 Support email strings as username
  bedita-app/models/account/user.php
Labels: Type - Bug, Topic - Core, Priority - High

#2053 Github workflows use `actions/cache@v4` and `actions/checkout@v4`
  .github/workflows/filter-components.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: Topic - Integration

#2054 Dependabot configuration
  .github/dependabot.yml
Labels: Topic - Integration

#2060 Dependabot config groups
  .github/dependabot.yml
Labels: Topic - Integration

#2064 Add index to async jobs table to help with sorting from Manager import view
  plugins/BEdita/Core/config/Migrations/20240227155754_AddIndexesToAsyncJobs.php
  plugins/BEdita/Core/config/Migrations/schema-dump-default.lock
  plugins/BEdita/Core/src/Model/Table/AsyncJobsTable.php
Labels: Type - Bug, Topic - Database, release:patch
